const fs = require('fs');
const path = require('path');

const testData = `.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............`;

const laboratories = (input) => {
    const lines = input.split('\n');
    const grid = lines.map(line => line.split(''));
    const start = grid.findIndex(line => line.includes('S'));
    const end = grid.findIndex(line => line.includes('E'));
    return start + end;
}

console.log('Part 1: 4277556', laboratories(testData));
// console.log('Part 2 (test): 3263827', laboratoriesPart2(testData));
// Read the input file
const inputPath = path.join(__dirname, 'input.txt');
try {   
    const data = fs.readFileSync(inputPath, 'utf8');
    // console.log('Part 1: 4277556', laboratories(data));
    // console.log('Part 2 (real):', laboratoriesPart2(data));
} catch (err) {
    console.error('Error reading the input file:', err);
}
